### ISSUE TITLE
download the source video

### ISSUE THREAD

**Issue by huge123** [husky-helen/FilmAnnotation#2]
Thank you very much for sharing your annotations, I am really interested in this work.
But I wonder if you can package all the source videos, and provide another way to download e.g. google drive, since I cannot access the youtube video due to the internet problem. 
Looking forward to your help.

**Comment by husky-helen** [comment]
> Thank you very much for sharing your annotations, I am really interested in this work.
> But I wonder if you can package all the source videos, and provide another way to download e.g. google drive, since I cannot access the youtube video due to the internet problem.
> Looking forward to your help.

Thanks for your request. Unfortunately, due to copyright we cannot share the video files with you. Those with youtube links are provided in the annotations.
